name: bangla_utilities
description: >-
  A utility library for Bangla date-time and number conversion.
version: 2.0.2
license: MIT
homepage: https://smj.xyz
repository: https://github.com/smjxpro/bangla_utilities_dart
issue_tracker: https://github.com/smjxpro/bangla_utilities_dart/issues
documentation: https://github.com/smjxpro/bangla_utilities_dart#readme

environment:
  sdk: ^3.4.0

dependencies:
  # No external dependencies (pure Dart).

dev_dependencies:
  test: ^1.24.0
  lints: ^6.0.0

topics:
  - date-time
  - number-conversion
  - bangla
  - utilities

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: